sudo: required

dist: trusty

language: python

services:
  - docker

install:
  - pip install coveralls

script:
  - docker-compose build leeloo
  - make leeloo_coverage

after_success:
  - coveralls

notifications:
  email: false
