sudo: required

dist: trusty

language: python

python:
  - "3.5"

services:
  - postgres
  - elasticsearch

addons:
  postgresql: "9.5"

install:
  - pip install --user -r leeloo/requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database datahub;' -U postgres
  - sleep 10

script:
  - pytest

after_success:
  - coveralls

notifications:
  email: false