sudo: required

dist: trusty

language: python

python:
  - "3.5"

services:
  - docker

script:
  - docker-compose build leeloo
  - docker-compose run leeloo pytest --cov=leeloo --cov-report term-missing --cov-config leeloo/.coveragerc leeloo/

after_success:
  - coveralls

notifications:
  email: false
