sudo: required

dist: trusty

language: python

env:
  - ES_HOST=es ES_PORT=9200 ES_INDEX=datahub KORBEN_HOST=korben KORBEN_PORT=8080 DATABASE_URL=postgresql://postgres@postgres-django/datahub

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-engine  # need at least 1.10, travis has 1.8.2 installed by default
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make test-leeloo
  - make test-odata-psql
  - make test-korben-unit
  - make test-korben-tier0

notifications:
  email: false
