sudo: required

dist: trusty

language: python

services:
  - docker

script:
  - docker-compose build leeloo
  - make leeloo_coverage
  - cd odata-psql && docker-compose up --build

after_success:
  - coveralls

notifications:
  email: false
