sudo: required

dist: trusty

language: python

services:
  - docker

script:
  - docker-compose build leeloo
  - make leeloo_coverage
  - make test-odata-psql
  - make test-korben

after_success:
  - coveralls

notifications:
  email: false
