sudo: required

dist: trusty

language: python

env:
  - ES_HOST=es ES_PORT=9200 ES_INDEX=datahub KORBEN_HOST=korben KORBEN_PORT=8080 DATABASE_URL=postgresql://postgres@postgres/datahub

services:
  - docker
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database datahub;' -U postgres

script:
  - make test-leeloo
  - make test-odata-psql
  - make test-korben-unit
  - make test-korben-tier0

notifications:
  email: false
