sudo: required

dist: trusty

language: python

services:
  - docker

script:
  # - docker-compose build leeloo
  # - make leeloo-tests
  - docker-compose build leeloo
  - make leeloo-tests
  - make test-odata-psql
  - make test-korben-unit
  - make test-korben-tier0

after_success:
  - coveralls

notifications:
  email: false
