version: "2"
services:
  leeloo:
    build:
      context: leeloo
    volumes:
      - ./leeloo:/app/leeloo
    environment:
      SECRET_KEY: foobar
      UI_SECRET: foobar
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    links:
      - postgres-django
      - es

  korben:
    build:
      context: korben
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ODATA_URL: ${DATABASE_ODATA_URL}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}

      # magical secrets below
      CDMS_ADFS_URL: ${CDMS_ADFS_URL}
      CDMS_BASE_URL: ${CDMS_BASE_URL}
      CDMS_USERNAME: ${CDMS_USERNAME}
      CDMS_PASSWORD: ${CDMS_PASSWORD}
      CDMS_COOKIE_KEY: ${CDMS_COOKIE_KEY}
      CDMS_RSTS_URL: ${CDMS_RSTS_URL}
      CDMS_COOKIE_PATH: ${CDMS_COOKIE_PATH}
      ODATA_ENTITY_CONTAINER_KEY: ${ODATA_ENTITY_CONTAINER_KEY}
    links:
      - postgres-django
      - postgres-odata
      - es
    volumes:
      - ./docker-volumes/korben/cache:/src/cache
      - ./docker-volumes/korben/cache:/cache
    command: korben bau
    ports:
      - "8080:8080"

  postgres-odata:
    build:
      context: postgres-namedatalen
    restart: always
    environment:
      - POSTGRES_DB=datahub_odata
    volumes:
      - ./docker-volumes/postgres-odata:/var/lib/postgresql/data

  postgres-django:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub
    volumes:
      - ./docker-volumes/postgres-django:/var/lib/postgresql/data

  es:
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"
