version: "2"
services:
  postgres-test:
    image: postgres
  korben-etl:
    build:
      context: korben
    depends_on:
      - postgres-test
    links:
      - postgres-test
    entrypoint: korben etl
  korben-test:
    environment: 
      KORBEN_CONF_PATH: jenkins.yml
    build:
      context: korben
    links:
      - postgres-test
      - korben-etl
    command: python setup.py test
