version: "2"
services:
  postgres:
    build:
      context: korben/korben/odata_psql
    restart: always
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
  korben-etl:
    build:
      context: korben
    depends_on:
      - postgres
    links:
      - postgres
    entrypoint: korben etl
  korben-test:
    build:
      context: korben
    depends_on:
      - postgres
    links:
      - postgres
    command: python setup.py test
