version: "2"
services:
  leeloo:
    build:
      context: leeloo
    volumes:
      - ./leeloo:/app/leeloo
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ES_INDEX: ${ES_INDEX}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      DJANGO_SECRET_KEY: foobar
      DJANGO_SENTRY_DSN: ${DJANGO_SENTRY_DSN}
      KORBEN_HOST: ${KORBEN_HOST}
      KORBEN_PORT: ${KORBEN_PORT}
      DATAHUB_SECRET: ${DATAHUB_SECRET}
      DEBUG: ${DJANGO_DEBUG}
      DJANGO_SETTINGS_MODULE: datahubapi.settings.production
    ports:
      - "8000:8000"
    entrypoint: dockerize -wait http://es:9200 -wait tcp://postgres-django:5432 -timeout 20s
    links:
      - postgres-django
      - es
      - korben
    command: /app/leeloo/start.sh

  korben:
    build:
      context: korben/test/dummy-container
    ports:
      - "8080:8080"

  postgres-odata:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub_odata
    volumes:
      - ./docker-volumes/postgres-odata:/var/lib/postgresql/data

  postgres-django:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub
    volumes:
      - ./docker-volumes/postgres-django:/var/lib/postgresql/data

  es:
    build:
      context: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - ./docker-volumes/es:/usr/share/elasticsearch/data

  redis:
    image: redis:3.2.5
    volumes:
      - ./docker-volumes/dummy-redis:/data
