version: "2"
services:
  postgres:
    build:
      context: korben/korben/odata_psql
    restart: always
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
  es:
    image: elasticsearch
    restart: always
  korben-sync-poll:
    build:
      context: korben
    depends_on:
      - postgres
      - es
    links:
      - postgres
      - es
    entrypoint: korben sync poll
