version: "2"
services:
  postgres:
    build:
      context: ./korben/postgres-namedatalen
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
    pg_data:
      external: true
    es_data:
      external: true