version: "2"
services:
  postgres:
    build:
      context: ./korben/postgres-namedatalen
    restart: always
    volumes:
        - pg_data:/var/lib/postgresql/data
  korben-poll:
    build:
      context: korben
    volumes:
        - pg_data:/var/lib/postgresql/data
    depends_on:
      - postgres
    links:
      - postgres


volumes:
    pg_data:
      external: true
