version: "2"
services:
  leeloo:
    build:
      context: leeloo
    environment:
      - SECRET_KEY=foobar
      - DATABASE_URL=postgres://postgres@postgres/datahub
    ports:
      - "8000:8000"
    links:
      - postgres
      - es

  korben-sync-poll:
    build:
      context: korben
    environment:
      - DATABASE_URL=postgres://postgres@postgres/datahub
      - DATABASE_ODATA_URL=postgres://postgres@postgres_odata/datahub_odata
    links:
      - postgres
      - postgres-odata
      - es
    command: korben sync poll

  korben-etl:
    build:
      context: korben
    environment:
      - DATABASE_URL=postgres://postgres@postgres/datahub
      - DATABASE_ODATA_URL=postgres://postgres@postgres_odata/datahub_odata
    ports:
      - "9000:8000"
    links:
      - postgres
      - postgres-odata
      - es
    command: korben etl

  korben-sync-ch:
    build:
      context: korben
    environment:
      - DATABASE_URL=postgres://postgres@postgres/datahub
      - DATABASE_ODATA_URL=postgres://postgres@postgres_odata/datahub_odata
    links:
      - postgres
      - postgres-odata
      - es
    command: korben sync ch

  postgres-odata:
    build:
      context: postgres-namedatalen
    restart: always
    environment:
      - POSTGRES_DB=datahub_odata
    volumes:
      - ./data/pgsql-odata:/var/lib/postgresql/data

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data

  es:
    image: elasticsearch
    restart: always
