version: "2"
services:
  postgres:
    build:
      context: ./korben/postgres-namedatalen
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  es:
    image: elasticsearch
    restart: always
  korben-poll:
    build:
      context: korben
    volumes:
        - pg_data:/var/lib/postgresql/data
    depends_on:
      - postgres
      - es
    links:
      - postgres
      - es
  leeloo:
    build:
      context: leeloo
    volumes:
        - pg_data:/var/lib/postgresql/data
    depends_on:
      - postgres
      - es
    links:
      - postgres
      - es


volumes:
    pg_data:
      external: true
    es_data:
      external: true
