version: "2"
services:
  leeloo:
    build:
      context: leeloo
    volumes:
      - ./leeloo:/app/leeloo
    environment:
      SECRET_KEY: foobar
      UI_SECRET: foobar
      DATABASE_URL: ${DATABASE_URL}
      ES_INDEX: test
    ports:
      - "8000:8000"
    links:
      - korben

  korben:
    build:
      context: korben/test/dummy-container
    ports:
      - "8080:8080"
