version: '2'
services:

  leeloo:
    build:
      context: leeloo
    volumes:
      - ./leeloo:/app/leeloo
    entrypoint: |
        dockerize -wait tcp://postgres:5432 -wait http://es:9200 -timeout 60s

    ports:
      - "8000:8000"
    depends_on:
      - korben
      - postgres
      - es
    links:
      - korben
      - postgres
      - es
    environment:
      SECRET_KEY: foobar
      UI_SECRET: foobar
      DATABASE_URL: postgresql://postgres@postgres/datahub
      ES_INDEX: test
      ES_HOST: es
      ES_PORT: 9200
      KORBEN_HOST: korben
      KORBEN_PORT: 8080

  korben:
    build:
      context: korben/test/dummy-container
    environment:
      DATABASE_URL: postgresql://postgres@postgres/test_datahub
    ports:
      - "8080:8080"

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub

  es:
    build:
      context: elasticsearch
    restart: always
    ports:
      - "9200:9200"
