version: "2"
services:
  leeloo:
    build:
      context: leeloo
    volumes:
      - ./leeloo:/app/leeloo
    environment:
      SECRET_KEY: foobar
      UI_SECRET: foobar
      DATABASE_URL: ${DATABASE_URL}
      ES_INDEX: test
    ports:
      - "8000:8000"
    links:
      - postgres-django
      - es
      - korben

  korben:
    build:
      context: korben/test/dummy-container
    links:
      - postgres-django
    ports:
      - "8080:8080"

  postgres-django:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub

  es:
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"
