version: "2"
services:

  datahub-src:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT}

  behave:
    build:
      context: behave
    links:
      - rhod
      - leeloo
      - korben
      - selenium
    depends_on:
      - rhod
      - leeloo
      - korben
      - selenium
    entrypoint: dockerize -wait http://rhod:3000/login -wait http://korben:8080/health/ -wait http://leeloo:8000/admin/login/ -timeout 300s
    environment:
      RHOD_PORT: 3000
      SELENIUM_PORT: 4444
      CDMS_USERNAME: ${CDMS_USERNAME}
      CDMS_PASSWORD: ${CDMS_PASSWORD}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}

  selenium:
    image: selenium/standalone-chrome-debug:3.0.1
    restart: always
    ports:
      - "4444:4444"
      - "5900:5900" # VNC port
    volumes:
      - /dev/shm:/dev/shm

  rhod:
    build:
      context: rhod
    volumes_from:
      - datahub-src
    links:
      - redis
      - leeloo
    depends_on:
      - redis
      - leeloo
    command: npm start
    ports:
      - "3000:3000"
    environment:
      API_ROOT: http://leeloo:8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://:@redis:6379
      API_CLIENT_ID: ${API_CLIENT_ID}
      API_CLIENT_SECRET: ${API_CLIENT_SECRET}

  leeloo:
    build:
      context: leeloo
    volumes_from:
      - datahub-src
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ES_INDEX: ${ES_INDEX}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      KORBEN_HOST: ${KORBEN_HOST}
      KORBEN_PORT: ${KORBEN_PORT}
      DATAHUB_SECRET: ${DATAHUB_SECRET}
      DEBUG: ${DJANGO_DEBUG}
      DJANGO_SETTINGS_MODULE: config.settings.behave
      BROKER_URL: redis://redis
      RESULT_BACKEND: redis://redis

      API_CLIENT_ID: ${API_CLIENT_ID}
      API_CLIENT_SECRET: ${API_CLIENT_SECRET}
      CDMS_USERNAME: ${CDMS_USERNAME}
      CDMS_PASSWORD: ${CDMS_PASSWORD}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}
    ports:
      - "8000:8000"
    entrypoint: dockerize -wait http://es:9200 -wait tcp://postgres-django:5432 -timeout 120s
    links:
      - postgres-django
      - es
      - korben
      - redis
    command: /app/leeloo/behave-start.sh

  korben:
    build:
      context: korben
    volumes_from:
      - datahub-src
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ODATA_URL: ${DATABASE_ODATA_URL}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      CDMS_ADFS_URL: ${CDMS_ADFS_URL}
      CDMS_BASE_URL: ${CDMS_BASE_URL}
      CDMS_USERNAME: ${CDMS_USERNAME}
      CDMS_PASSWORD: ${CDMS_PASSWORD}
      CDMS_COOKIE_KEY: ${CDMS_COOKIE_KEY}
      CDMS_RSTS_URL: ${CDMS_RSTS_URL}
      CDMS_COOKIE_PATH: ${CDMS_COOKIE_PATH}
      ODATA_ENTITY_CONTAINER_KEY: ${ODATA_ENTITY_CONTAINER_KEY}
      DATAHUB_SECRET: ${DATAHUB_SECRET}
      KORBEN_SENTRY_DSN: ${KORBEN_SENTRY_DSN}
    links:
      - postgres-django
      - postgres-odata
      - es
      - redis
    command: korben bau
    ports:
      - "8080:8080"

  postgres-odata:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub_odata

  postgres-django:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub

  es:
    image: elasticsearch:2.4.1
    restart: always
    ports:
      - "9200:9200"

  redis:
    image: redis:3.2.5
    restart: always
    ports:
      - "6379:6379"
