swagger: '2.0'
info:
  description: Data Hub Company V2
  version: 1.0.0
  title: Company API
  # put the contact info for your development or API team
  contact:
    email: jim.smith@digital.trade.gov.uk
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

# all paths will be relative to the basePath specified
basePath: /v2

# tags are used for organizing operations
tags:
- name: public
  description: API open to DH client
- name: company
  description: Belongs to company operations in DH
schemes:
- https
paths:
  /company/{companyId}:
    get:
      tags:
      - company
      summary: Returns a company from the Data Hub repository
      operationId: getcompany
      description: |
        Passing in a company UUID returns a Data Hub company object
      produces:
      - application/vnd.api+json
      parameters:
      - in: path
        name: companyId
        description: UUID for a Data Hub company
        required: true
        type: string
        format: uuid
      responses:
        200:
          description: JSON API formatted company object
          schema:
            $ref: '#/definitions/Company'
        400:
          description: bad input parameter
        404:
          description: company does not exist
    put:
      tags:
      - company
      summary: updates a company, creating a new one if not found
      operationId: updateCompany
      description: Updates an existing company
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: path
        name: companyId
        description: UUID for a Data Hub company
        type: string
        required: true
      - in: body
        name: company
        description: Company data to update
        required: true
        schema:
          $ref: '#/definitions/Company'
      responses:
        200:
          description: item updated
        201:
          description: item created
        400:
          description: invalid input, object invalid
  /company:
    post:
      tags:
      - company
      summary: adds a Data Hub company
      operationId: addCompany
      description: Adds a Data Hub company from a Companies House company
      consumes:
      - application/vnd.api+json
      produces:
      - application/vnd.api+json
      parameters:
      - in: body
        name: company
        description: Company to add
        required: true
        schema:
          $ref: '#/definitions/Company'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        409:
          description: company already exists
# Placeholder for future expansion
#  /companies/:
#    get:
#      tags: 
#      - company
#      summary: returns a list of company objects
#      operationId: getCompanies
#      description: returns a list of companies predicated on some filter - placeholder for future expansion
#      consumes:
#      - application/vnd.api+json
#      produces:
#      - application/vnd.api+json
#      responses:
#        200:
#          description: List of companies
#          schema:
#            type: array
#            items:
#              $ref: '#/definitions/Company'
definitions:
  Company:
    type: object
    description: A flat representation of the Data Hub company object
    required:
    - data
    properties:
      data: 
        title: Company
        type: object
        required:
        - name
        - registered_address_1
        - registered_address_town
        - registered_address_country
        - business_type
        - sector
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "EXAMPLE Ltd"
          trading_name:
            type: string
            example: "Example Trading"
          uk_based:
            type: boolean
          registered_address_1:
            type: string
            example: "123 HIGH STREET"
          registered_address_2:
            type: string
            example: "AREA"
          registered_address_3:
            type: string
            example: "SUBTOWN"
          registered_address_4:
            type: string
            example: "SUBREGION"
          registered_address_town:
            type: string
            example: "ANYTOWN"
          registered_address_county:
            type: string
            example: "ANYSHIRE"
          registered_address_postcode:
            type: string
            example: "AB1 2CD"
          created_on:
            type: string
            format: date-time
            example: 2014-07-23T10:36:04
          modified_on:
            type: string
            format: date-time
            example: 2014-07-23T10:36:04
          archived:
            type: boolean
          archived_on:
            type: string
            format: date-time
            example: 2014-07-23T10:36:04
          archived_reason:
            type: string
            example: "Company dissolved"
          archived_by:
            type: string
            example: "A N Advisor"
          company_number:
            type: string
            example: 12345678
          alias:
            type: string
            example: "EXAMPLE TRADING"
          lead:
            type: boolean
          description:
            type: string
            example: "MANUFACTURER OF WIDGETS AND DOODADS"
          website:
            type: string
            example: "http://www.example.com"
          trading_address_1:
            type: string
            example: "123 HIGH STREET"
          trading_address_2:
            type: string
            example: "AREA"
          trading_address_3:
            type: string
            example: "SUBTOWN"
          trading_address_4:
            type: string
            example: "SUBREGION"
          trading_address_town:
            type: string
            example: "ANYTOWN"
          trading_address_county:
            type: string
            example: "ANYSHIRE"
          trading_address_postcode:
            type: string
            example: "AB1 2CD"
          headquarter_type:
            type: string
            example: "UK Headquarters"
          relationships:
            $ref: '#/definitions/CompanyRelationships'
  CompanyRelationships:
    type: object
    properties:
      account_manager:
        $ref: '#/definitions/Adviser'
      business_type:
        $ref: '#/definitions/BusinessType'
      children:
        $ref: '#/definitions/CompanyKeyArray'
      classification:
        $ref: '#/definitions/Classification'
      contacts:
        $ref: '#/definitions/ContactArray'
      employee_range:
        $ref: '#/definitions/EmployeeRange'
      export_to_countries:
        $ref: '#/definitions/CountryArray'
      future_interest_countries:
        $ref: '#/definitions/CountryArray'
      interactions:
        $ref: '#/definitions/InteractionArray'
      one_list_owner:
        $ref: '#/definitions/Adviser'
      parents:
        $ref: '#/definitions/CompanyKeyArray'
      registered_address_country:
          $ref: '#/definitions/Country'
      sector:
        $ref: '#/definitions/Sector'
      trading_address_country:
          $ref: '#/definitions/Country'
      turnover_range:
        $ref: '#/definitions/TurnoverRange'
      uk_region:
        $ref: '#/definitions/UKRegion'
  Adviser:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Fred Jones"
  BusinessType:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Private"
  Classification:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "10519"
  CompanyKey:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "EXAMPLE LTD" 
  CompanyKeyArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/CompanyKey'
  Contact:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Fred Bloggs"
  ContactArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Contact'
  Country:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Fredonia"
  CountryArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Country'
  Interaction:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Subject of Interaction"
  InteractionArray:
    type: object
    required:
    - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Interaction'
  EmployeeRange:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "1 to 9"
  Sector:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "Manufacturing"
  TurnoverRange:
    type: object
    required:
    - data
    properties:
      data:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
            example: "...1 to 1.3m"
  UKRegion:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required: 
          - id
          - name
        properties:
          id:
            type: string
            format: uuid
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
          name:
            type: string
            example: "England"
