language: python

python:
  - "3.5"

services:
  - postgresql

env:
  - DJANGO_VERSION=1.10

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database datahub;' -U postgres

script: python manage.py test

